theme: jekyll-theme-cayman
title: Singapore MATSim Scenario
description: A MATSim Scenario development for Singapore by Adaptive Mobility, Infrastructure and Land-use (AMIL) module - FCL Global - ETH Zurich
